// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3PmtT6-7VAGRmEXOYTERhMwWN0obSG-Q',
    appId: '1:499004763829:web:176565ec6206daf9f318fc',
    messagingSenderId: '499004763829',
    projectId: 'challenge-itamar',
    authDomain: 'challenge-itamar.firebaseapp.com',
    storageBucket: 'challenge-itamar.appspot.com',
    measurementId: 'G-1GKSQPCG59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXzTgIg8NpNLAEs2ulpTUmj5YkpXwbKSY',
    appId: '1:499004763829:android:4eb1324f3a91e59ff318fc',
    messagingSenderId: '499004763829',
    projectId: 'challenge-itamar',
    storageBucket: 'challenge-itamar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkwyaWwhjiu9pBLp2dsrFlrC0Ozxeh_bU',
    appId: '1:499004763829:ios:f93d12f40361a3d4f318fc',
    messagingSenderId: '499004763829',
    projectId: 'challenge-itamar',
    storageBucket: 'challenge-itamar.appspot.com',
    iosBundleId: 'com.example.challenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkwyaWwhjiu9pBLp2dsrFlrC0Ozxeh_bU',
    appId: '1:499004763829:ios:f93d12f40361a3d4f318fc',
    messagingSenderId: '499004763829',
    projectId: 'challenge-itamar',
    storageBucket: 'challenge-itamar.appspot.com',
    iosBundleId: 'com.example.challenge',
  );
}
